name: Close stale issues
on:
  schedule:
    - cron: 30 1 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: ""
          exempt-pr-labels: enhancement,bug,work-in-progress
