repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: format
        name: format
        entry: poetry run task format
        language: system
        types: [python]
      - id: lint
        name: lint
        entry: poetry run task lint
        language: system
        types: [python]
      - id: test
        name: test
        entry: poetry run task test
        language: system
        types: [python]
