repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        require_serial: true
        types_or: [python, pyi]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8
        entry: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      types_or: [cython, pyi, python]
      args: ['--filter-files']

  - repo: https://github.com/PyCQA/pylint
    rev: v2.17.5
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      require_serial: true

  - repo: local
    hooks:
      - id: test
        name: test
        entry: poetry run task full_test
        language: system
        pass_filenames: false
        types: [python]
