name: test

on: pull_request

env:
  TEST_TAG: monopoly-test:latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Git Crypt
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install git-crypt
          echo '${{ secrets.GIT_CRYPT_KEY }}' | base64 --decode > /tmp/git-crypt-key
          git-crypt unlock /tmp/git-crypt-key
          rm /tmp/git-crypt-key

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: test
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha,scope=test
          cache-to: type=gha,mode=max,scope=test

      - name: Test
        run: docker run --rm ${{ env.TEST_TAG }}
